version: "3.5"

services:
  app:
    command: bash -c "poetry run python main.py"
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"  # 5432 PORT in my PC already bind
    env_file:
      - ./.env

volumes:
  postgres_data:
